<?php

namespace Database\Seeders;

use App\Models\UiSetting;
use Illuminate\Database\Seeder;

class UiSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // CATÉGORIE: POLICES
            [
                'category' => 'fonts',
                'key' => 'font_size_base',
                'value' => '0.875',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille de police de base',
                'description' => 'Taille de police globale de l\'application',
                'min_value' => 0.75,
                'max_value' => 1.25,
                'default_value' => '0.875',
            ],
            [
                'category' => 'fonts',
                'key' => 'font_size_h1',
                'value' => '1.75',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille H1',
                'description' => 'Taille des titres H1',
                'min_value' => 1.5,
                'max_value' => 3,
                'default_value' => '1.75',
            ],
            [
                'category' => 'fonts',
                'key' => 'font_size_h2',
                'value' => '1.5',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille H2',
                'description' => 'Taille des titres H2',
                'min_value' => 1.25,
                'max_value' => 2.5,
                'default_value' => '1.5',
            ],
            [
                'category' => 'fonts',
                'key' => 'font_size_h3',
                'value' => '1.25',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille H3',
                'description' => 'Taille des titres H3',
                'min_value' => 1,
                'max_value' => 2,
                'default_value' => '1.25',
            ],
            [
                'category' => 'fonts',
                'key' => 'font_size_h4',
                'value' => '1.1',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille H4',
                'description' => 'Taille des titres H4',
                'min_value' => 0.9,
                'max_value' => 1.5,
                'default_value' => '1.1',
            ],
            [
                'category' => 'fonts',
                'key' => 'font_size_h5',
                'value' => '1',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille H5',
                'description' => 'Taille des titres H5',
                'min_value' => 0.85,
                'max_value' => 1.25,
                'default_value' => '1',
            ],

            // CATÉGORIE: ESPACEMENTS
            [
                'category' => 'spacing',
                'key' => 'sidebar_width',
                'value' => '230',
                'unit' => 'px',
                'type' => 'number',
                'label' => 'Largeur de la sidebar',
                'description' => 'Largeur de la barre latérale',
                'min_value' => 200,
                'max_value' => 300,
                'default_value' => '230',
            ],
            [
                'category' => 'spacing',
                'key' => 'sidebar_collapsed_width',
                'value' => '65',
                'unit' => 'px',
                'type' => 'number',
                'label' => 'Largeur sidebar réduite',
                'description' => 'Largeur de la barre latérale réduite',
                'min_value' => 50,
                'max_value' => 100,
                'default_value' => '65',
            ],
            [
                'category' => 'spacing',
                'key' => 'topbar_height',
                'value' => '50',
                'unit' => 'px',
                'type' => 'number',
                'label' => 'Hauteur de la barre supérieure',
                'description' => 'Hauteur de la topbar',
                'min_value' => 45,
                'max_value' => 70,
                'default_value' => '50',
            ],
            [
                'category' => 'spacing',
                'key' => 'main_padding',
                'value' => '1.25',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding du contenu principal',
                'description' => 'Espacement interne du contenu principal',
                'min_value' => 0.5,
                'max_value' => 3,
                'default_value' => '1.25',
            ],
            [
                'category' => 'spacing',
                'key' => 'card_padding',
                'value' => '1',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding des cartes',
                'description' => 'Espacement interne des cartes',
                'min_value' => 0.5,
                'max_value' => 2,
                'default_value' => '1',
            ],
            [
                'category' => 'spacing',
                'key' => 'content_frame_padding',
                'value' => '1.25',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding du cadre de contenu',
                'description' => 'Espacement interne du cadre de contenu',
                'min_value' => 0.75,
                'max_value' => 3,
                'default_value' => '1.25',
            ],

            // CATÉGORIE: ICÔNES
            [
                'category' => 'icons',
                'key' => 'icon_size_default',
                'value' => '0.875',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille d\'icône par défaut',
                'description' => 'Taille des icônes standards',
                'min_value' => 0.75,
                'max_value' => 1.5,
                'default_value' => '0.875',
            ],
            [
                'category' => 'icons',
                'key' => 'icon_size_stats',
                'value' => '1.75',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille icônes statistiques',
                'description' => 'Taille des icônes dans les cartes de statistiques',
                'min_value' => 1.5,
                'max_value' => 3,
                'default_value' => '1.75',
            ],
            [
                'category' => 'icons',
                'key' => 'icon_size_topbar',
                'value' => '34',
                'unit' => 'px',
                'type' => 'number',
                'label' => 'Taille icônes topbar',
                'description' => 'Taille des icônes dans la barre supérieure',
                'min_value' => 30,
                'max_value' => 50,
                'default_value' => '34',
            ],
            [
                'category' => 'icons',
                'key' => 'logo_size',
                'value' => '65',
                'unit' => 'px',
                'type' => 'number',
                'label' => 'Taille du logo',
                'description' => 'Taille du logo dans la sidebar',
                'min_value' => 50,
                'max_value' => 100,
                'default_value' => '65',
            ],

            // CATÉGORIE: BOUTONS
            [
                'category' => 'buttons',
                'key' => 'button_font_size',
                'value' => '0.875',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille de police des boutons',
                'description' => 'Taille du texte dans les boutons',
                'min_value' => 0.75,
                'max_value' => 1.25,
                'default_value' => '0.875',
            ],
            [
                'category' => 'buttons',
                'key' => 'button_padding_y',
                'value' => '0.5',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding vertical des boutons',
                'description' => 'Espacement vertical interne des boutons',
                'min_value' => 0.25,
                'max_value' => 1,
                'default_value' => '0.5',
            ],
            [
                'category' => 'buttons',
                'key' => 'button_padding_x',
                'value' => '1',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding horizontal des boutons',
                'description' => 'Espacement horizontal interne des boutons',
                'min_value' => 0.5,
                'max_value' => 2,
                'default_value' => '1',
            ],
            [
                'category' => 'buttons',
                'key' => 'button_border_radius',
                'value' => '6',
                'unit' => 'px',
                'type' => 'number',
                'label' => 'Arrondi des boutons',
                'description' => 'Rayon des coins arrondis des boutons',
                'min_value' => 0,
                'max_value' => 20,
                'default_value' => '6',
            ],

            // CATÉGORIE: FORMULAIRES
            [
                'category' => 'forms',
                'key' => 'input_font_size',
                'value' => '0.875',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille police des champs',
                'description' => 'Taille du texte dans les champs de formulaire',
                'min_value' => 0.75,
                'max_value' => 1.25,
                'default_value' => '0.875',
            ],
            [
                'category' => 'forms',
                'key' => 'input_padding_y',
                'value' => '0.5',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding vertical des champs',
                'description' => 'Espacement vertical interne des champs',
                'min_value' => 0.25,
                'max_value' => 1,
                'default_value' => '0.5',
            ],
            [
                'category' => 'forms',
                'key' => 'input_padding_x',
                'value' => '0.75',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding horizontal des champs',
                'description' => 'Espacement horizontal interne des champs',
                'min_value' => 0.5,
                'max_value' => 1.5,
                'default_value' => '0.75',
            ],

            // CATÉGORIE: NAVIGATION
            [
                'category' => 'navigation',
                'key' => 'nav_link_padding_y',
                'value' => '0.6',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding vertical liens navigation',
                'description' => 'Espacement vertical des liens de navigation',
                'min_value' => 0.4,
                'max_value' => 1.2,
                'default_value' => '0.6',
            ],
            [
                'category' => 'navigation',
                'key' => 'nav_link_padding_x',
                'value' => '0.875',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Padding horizontal liens navigation',
                'description' => 'Espacement horizontal des liens de navigation',
                'min_value' => 0.5,
                'max_value' => 1.5,
                'default_value' => '0.875',
            ],
            [
                'category' => 'navigation',
                'key' => 'nav_link_font_size',
                'value' => '0.875',
                'unit' => 'rem',
                'type' => 'number',
                'label' => 'Taille police navigation',
                'description' => 'Taille du texte des liens de navigation',
                'min_value' => 0.75,
                'max_value' => 1.25,
                'default_value' => '0.875',
            ],
        ];

        foreach ($settings as $setting) {
            UiSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
